### PR TITLE
fix: strict types error

### LINKED ISSUE #176: Fix remaining strict types errors
With Drupal core moving towards strict types, [more info](https://github.com/localgovdrupal/localgov/issues/685) we should fix the remaining errors suppressed in the phpstan baseline.

```
 ------ -------------------------------------------------------------------------------
  Line   modules/contrib/localgov_guides/src/Plugin/PreviewLinkAutopopulate/Guides.php
 ------ -------------------------------------------------------------------------------
  39     Variable $overview might not be defined.
  42     Variable $overview might not be defined.
 ------ -------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by millnut**
## What does this change?

Fixes #176

### CODE REVIEW

File: src/Plugin/PreviewLinkAutopopulate/Guides.php [hunk 1]
```diff
@@ -36,13 +38,16 @@ public function getPreviewEntities(): array {
...
       $overview = $node->get('localgov_guides_parent')->entity;
     }
-    $guide_nodes[] = $overview;
 
-    // Find guide pages.
-    $guide_pages = $overview->get('localgov_guides_pages')->referencedEntities();
-    foreach ($guide_pages as $guide_page) {
-      if ($guide_page instanceof NodeInterface && $guide_page->access('view')) {
-        $guide_nodes[] = $guide_page;
+    if ($overview instanceof Node) {
```
Comment (ekes) [inline src/Plugin/PreviewLinkAutopopulate/Guides.php]: Nitpik: this should be NodeInterface I think.

Comment (finnlewis) [reply src/Plugin/PreviewLinkAutopopulate/Guides.php]: And one more @millnut  :)

Comment (millnut) [reply src/Plugin/PreviewLinkAutopopulate/Guides.php]: 👍 @ekes I've now updated this

**Review by ekes — APPROVED** [review]
