### PR TITLE
Check for body field before acting on it

### LINKED ISSUE #188: PageHeaderSubscriber.php assumes a guide page will always have a body field
If there is no body field on the Guide Page content type we get a WSOD with the following error: 

```
InvalidArgumentException: Field body is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 616 of core/lib/Drupal/Core/Entity/ContentEntityBase.php). 
```

### PR DESCRIPTION
**Pull request by markconroy**
Closes #188 

## What does this change?

Simple check to see if the body field exists before we act on it.

## How to test

Delete body field from guide page content type, the pageHeader block will cause a WSOD. Checkout this branch, clear your cache, and then refresh your page and the pageHeader block should be working again.

### CODE REVIEW

File: tests/src/Functional/PageHeaderBlockTest.php [hunk 1]
```diff
@@ -106,6 +111,23 @@ public function testGuidePageHeaderBlock() {
...
+    // Check lede.
+    $this->drupalGet($page->toUrl()->toString());
+    $this->assertSession()->responseContains('Lede to show');
+    // Remove body field, check title and no lede.
+    $field_definitions = \Drupal::service('entity_field.manager')->getFieldDefinitions('node', 'localgov_guides_overview');
+    $field_definitions['body']->delete();
+    $this->drupalGet($overview->toUrl()->toString());
+    $this->assertSession()->responseNotContains('Lede to show');
+    // @todo remove this.
+    drupal_flush_all_caches();
```
Comment (ekes) [inline tests/src/Functional/PageHeaderBlockTest.php:125]: Test adds checks lede shows in the first place and confirms it works when the field is removed.

However it needs the cache clear, so I'll create a follow-up issue about the caching of the block (guessing it wants cache metadata, rather than just cache tags).

**Review by ekes — APPROVED** [review]
Approved because the test proves it. ~~But don't merge till there's a follow-up linked.~~ Follow-up posted.

File: tests/src/Functional/PageHeaderBlockTest.php (hunk 1 above)
Comment (ekes) [reply tests/src/Functional/PageHeaderBlockTest.php:125]: Issue https://github.com/localgovdrupal/localgov_core/issues/290
